from PyQt4 import QtCore, QtGui
import sys
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WeatherForcast(QtGui.QWidget):
    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.setupUi(self)
        
    def setupUi(self, WeatherForcast):
        WeatherForcast.setObjectName(_fromUtf8("WeatherForcast"))
        WeatherForcast.resize(572, 570)
        font = QtGui.QFont()
        font.setUnderline(True)
        WeatherForcast.setFont(font)
        WeatherForcast.setStyleSheet(_fromUtf8(""))
        
        # TOP_MIDDLE FRAME
        self.MIDDLE_FRAME = QtGui.QFrame(WeatherForcast)
        self.MIDDLE_FRAME.setGeometry(QtCore.QRect(0, 0, 571, 411))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.MIDDLE_FRAME.setFont(font)
        self.MIDDLE_FRAME.setStyleSheet(_fromUtf8("Background:url(:/BG_PIC/BACKGROUND_TOP.jpg)"))
        self.MIDDLE_FRAME.setFrameShape(QtGui.QFrame.StyledPanel)
        self.MIDDLE_FRAME.setFrameShadow(QtGui.QFrame.Raised)
        self.MIDDLE_FRAME.setObjectName(_fromUtf8("MIDDLE_FRAME"))
        
        # PLACE LABEL
        self.PLACE_LABEL = QtGui.QLabel(self.MIDDLE_FRAME)
        self.PLACE_LABEL.setGeometry(QtCore.QRect(140, 90, 201, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.PLACE_LABEL.setFont(font)
        self.PLACE_LABEL.setStyleSheet(_fromUtf8("Background:url(:/BG_PIC/SMALL_BACKGROUND.png)"))
        self.PLACE_LABEL.setObjectName(_fromUtf8("PLACE_LABEL"))
        self.DATE_LABEL = QtGui.QLabel(self.MIDDLE_FRAME)
        self.DATE_LABEL.setGeometry(QtCore.QRect(140, 120, 161, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        
        # DATA LABEL
        self.DATE_LABEL.setFont(font)
        self.DATE_LABEL.setStyleSheet(_fromUtf8("Background:url(:/BG_PIC/SMALL_BACKGROUND.png)"))
        self.DATE_LABEL.setObjectName(_fromUtf8("DATE_LABEL"))
        
        # PLACE LINE EDIT BOX
        self.PLACE_LINE_EDIT_BOX = QtGui.QLineEdit(self.MIDDLE_FRAME)
        self.PLACE_LINE_EDIT_BOX.setGeometry(QtCore.QRect(250, 100, 211, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.PLACE_LINE_EDIT_BOX.setFont(font)
        self.PLACE_LINE_EDIT_BOX.setStyleSheet(_fromUtf8("background:rgb(255, 255, 255)"))
        self.PLACE_LINE_EDIT_BOX.setObjectName(_fromUtf8("PLACE_LINE_EDIT_BOX"))
        
        # DATA EDIT PANEL
        self.DATE_EDIT = QtGui.QDateEdit(self.MIDDLE_FRAME)
        self.DATE_EDIT.setGeometry(QtCore.QRect(250, 140, 211, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.DATE_EDIT.setFont(font)
        self.DATE_EDIT.setCalendarPopup(True)
        self.DATE_EDIT.setObjectName(_fromUtf8("DATE_EDIT"))
        
        # OK BUTTON
        self.OK_BUTTON = QtGui.QPushButton(self.MIDDLE_FRAME)
        self.OK_BUTTON.setGeometry(QtCore.QRect(254, 180, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.OK_BUTTON.setFont(font)
        self.OK_BUTTON.setObjectName(_fromUtf8("OK_BUTTON"))
        
        # E-MAIL BUTTON
        self.EMAIL_BUTTON = QtGui.QPushButton(self.MIDDLE_FRAME)
        self.EMAIL_BUTTON.setGeometry(QtCore.QRect(350, 180, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.EMAIL_BUTTON.setFont(font)
        self.EMAIL_BUTTON.setObjectName(_fromUtf8("EMAIL_BUTTON"))
        
        # TOP WEATHER LABEL
        self.WEATHER_LABEL = QtGui.QLabel(self.MIDDLE_FRAME)
        self.WEATHER_LABEL.setGeometry(QtCore.QRect(200, 0, 371, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(26)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.WEATHER_LABEL.setFont(font)
        self.WEATHER_LABEL.setAutoFillBackground(False)
        self.WEATHER_LABEL.setStyleSheet(_fromUtf8("Background:url(:/BG_PIC/SMALL_BACKGROUND.png)"))
        self.WEATHER_LABEL.setObjectName(_fromUtf8("WEATHER_LABEL"))
        
        # FORCAST LABEL
        self.FORCAST_LABEL = QtGui.QLabel(self.MIDDLE_FRAME)
        self.FORCAST_LABEL.setGeometry(QtCore.QRect(380, 40, 201, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Brush Script MT"))
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.FORCAST_LABEL.setFont(font)
        self.FORCAST_LABEL.setStyleSheet(_fromUtf8("Background:\n""url(:/BG_PIC/SMALL_BACKGROUND.png)"))
        self.FORCAST_LABEL.setObjectName(_fromUtf8("FORCAST_LABEL"))
        self.label = QtGui.QLabel(self.MIDDLE_FRAME)
        self.label.setGeometry(QtCore.QRect(10, 80, 551, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Algerian"))
        font.setPointSize(36)
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        
        # GRAPHIC BUTTON
        self.GRAPH_BUTTON = QtGui.QPushButton(self.MIDDLE_FRAME)
        self.GRAPH_BUTTON.setGeometry(QtCore.QRect(440, 180, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.GRAPH_BUTTON.setFont(font)
        self.GRAPH_BUTTON.setObjectName(_fromUtf8("GRAPH_BUTTON"))
        
        # CURRENT  TEMPERATURE LINE EDIT BOX 
        self.CURRENT_TEMP_LINE_EDIT_BOX = QtGui.QLineEdit(self.MIDDLE_FRAME)
        self.CURRENT_TEMP_LINE_EDIT_BOX.setGeometry(QtCore.QRect(150, 230, 131, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.CURRENT_TEMP_LINE_EDIT_BOX.setFont(font)
        self.CURRENT_TEMP_LINE_EDIT_BOX.setStyleSheet(_fromUtf8("background:rgb(255, 255, 255)"))
        self.CURRENT_TEMP_LINE_EDIT_BOX.setObjectName(_fromUtf8("CURRENT_TEMP_LINE_EDIT_BOX"))
        
        # CURRENT TEMPERATURE LABEL
        self.CURRENT_TEMPERATURE_LABEL = QtGui.QLabel(self.MIDDLE_FRAME)
        self.CURRENT_TEMPERATURE_LABEL.setGeometry(QtCore.QRect(10, 220, 131, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.CURRENT_TEMPERATURE_LABEL.setFont(font)
        self.CURRENT_TEMPERATURE_LABEL.setStyleSheet(_fromUtf8("Background:url(:/BG_PIC/SMALL_BACKGROUND.png)"))
        self.CURRENT_TEMPERATURE_LABEL.setObjectName(_fromUtf8("CURRENT_TEMPERATURE_LABEL"))
        self.label_2 = QtGui.QLabel(self.MIDDLE_FRAME)
        self.label_2.setGeometry(QtCore.QRect(10, 210, 551, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Algerian"))
        font.setPointSize(36)
        font.setUnderline(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        
        # CURRENT DATA LABEL
        self.CURRENT_DATA_LABEL = QtGui.QLabel(self.MIDDLE_FRAME)
        self.CURRENT_DATA_LABEL.setGeometry(QtCore.QRect(10, 190, 181, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.CURRENT_DATA_LABEL.setFont(font)
        self.CURRENT_DATA_LABEL.setStyleSheet(_fromUtf8("Background:url(:/BG_PIC/SMALL_BACKGROUND.png)"))
        self.CURRENT_DATA_LABEL.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.CURRENT_DATA_LABEL.setObjectName(_fromUtf8("CURRENT_DATA_LABEL"))
        
        # CURRENT  PRESSURE LINE EDIT BOX 
        self.CURRENT_PRESSURE_LINE_EDIT_BOX = QtGui.QLineEdit(self.MIDDLE_FRAME)
        self.CURRENT_PRESSURE_LINE_EDIT_BOX.setGeometry(QtCore.QRect(150, 260, 131, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.CURRENT_PRESSURE_LINE_EDIT_BOX.setFont(font)
        self.CURRENT_PRESSURE_LINE_EDIT_BOX.setStyleSheet(_fromUtf8("background:rgb(255, 255, 255)"))
        self.CURRENT_PRESSURE_LINE_EDIT_BOX.setObjectName(_fromUtf8("CURRENT_PRESSURE_LINE_EDIT_BOX"))
        self.CURRENT_PRESSURE_LABEL = QtGui.QLabel(self.MIDDLE_FRAME)
        self.CURRENT_PRESSURE_LABEL.setGeometry(QtCore.QRect(10, 250, 131, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        
        # CURRENT PRESSURE LABEL
        self.CURRENT_PRESSURE_LABEL.setFont(font)
        self.CURRENT_PRESSURE_LABEL.setStyleSheet(_fromUtf8("Background:url(:/BG_PIC/SMALL_BACKGROUND.png)"))
        self.CURRENT_PRESSURE_LABEL.setObjectName(_fromUtf8("CURRENT_PRESSURE_LABEL"))
        
        # CURRENT  PRECIPITATION LINE EDIT BOX 
        self.CURRENT_PRECIPITATION_EDIT_BOX = QtGui.QLineEdit(self.MIDDLE_FRAME)
        self.CURRENT_PRECIPITATION_EDIT_BOX.setGeometry(QtCore.QRect(150, 290, 131, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.CURRENT_PRECIPITATION_EDIT_BOX.setFont(font)
        self.CURRENT_PRECIPITATION_EDIT_BOX.setStyleSheet(_fromUtf8("background:rgb(255, 255, 255)"))
        self.CURRENT_PRECIPITATION_EDIT_BOX.setObjectName(_fromUtf8("CURRENT_PRECIPITATION_EDIT_BOX"))
        self.CURRENT_PRECIPITATION_LABEL = QtGui.QLabel(self.MIDDLE_FRAME)
        self.CURRENT_PRECIPITATION_LABEL.setGeometry(QtCore.QRect(10, 280, 131, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        
        # CURRENT PRECIPITATION LABEL
        self.CURRENT_PRECIPITATION_LABEL.setFont(font)
        self.CURRENT_PRECIPITATION_LABEL.setStyleSheet(_fromUtf8("Background:url(:/BG_PIC/SMALL_BACKGROUND.png)"))
        self.CURRENT_PRECIPITATION_LABEL.setObjectName(_fromUtf8("CURRENT_PRECIPITATION_LABEL"))
        
         # CURRENT  HUMIDITY LINE EDIT BOX 
        self.CURRENT_HUMIDITY_LINE_EDIT_BOX = QtGui.QLineEdit(self.MIDDLE_FRAME)
        self.CURRENT_HUMIDITY_LINE_EDIT_BOX.setGeometry(QtCore.QRect(410, 230, 131, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.CURRENT_HUMIDITY_LINE_EDIT_BOX.setFont(font)
        self.CURRENT_HUMIDITY_LINE_EDIT_BOX.setStyleSheet(_fromUtf8("background:rgb(255, 255, 255)"))
        self.CURRENT_HUMIDITY_LINE_EDIT_BOX.setObjectName(_fromUtf8("CURRENT_HUMIDITY_LINE_EDIT_BOX"))
        
        # CURRENT SUMMARY LABEL
        self.CURRENT_SUMMARY_LABEL = QtGui.QLabel(self.MIDDLE_FRAME)
        self.CURRENT_SUMMARY_LABEL.setGeometry(QtCore.QRect(300, 250, 111, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.CURRENT_SUMMARY_LABEL.setFont(font)
        self.CURRENT_SUMMARY_LABEL.setStyleSheet(_fromUtf8("Background:url(:/BG_PIC/SMALL_BACKGROUND.png)"))
        self.CURRENT_SUMMARY_LABEL.setObjectName(_fromUtf8("CURRENT_SUMMARY_LABEL"))
        
        # CURRENT HUMIDITY LABEL
        self.CURRENT_HUMIDITY_LABEL = QtGui.QLabel(self.MIDDLE_FRAME)
        self.CURRENT_HUMIDITY_LABEL.setGeometry(QtCore.QRect(300, 220, 111, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.CURRENT_HUMIDITY_LABEL.setFont(font)
        self.CURRENT_HUMIDITY_LABEL.setStyleSheet(_fromUtf8("Background:url(:/BG_PIC/SMALL_BACKGROUND.png)"))
        self.CURRENT_HUMIDITY_LABEL.setObjectName(_fromUtf8("CURRENT_HUMIDITY_LABEL"))
        
        # CURRENT  SUMMARY LINE EDIT BOX 
        self.CURRENT_SUMMARY_LINE_EDIT_BOX = QtGui.QLineEdit(self.MIDDLE_FRAME)
        self.CURRENT_SUMMARY_LINE_EDIT_BOX.setGeometry(QtCore.QRect(410, 260, 131, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.CURRENT_SUMMARY_LINE_EDIT_BOX.setFont(font)
        self.CURRENT_SUMMARY_LINE_EDIT_BOX.setStyleSheet(_fromUtf8("background:rgb(255, 255, 255)"))
        self.CURRENT_SUMMARY_LINE_EDIT_BOX.setObjectName(_fromUtf8("CURRENT_SUMMARY_LINE_EDIT_BOX"))
        self.label_5 = QtGui.QLabel(self.MIDDLE_FRAME)
        self.label_5.setGeometry(QtCore.QRect(10, 350, 551, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Algerian"))
        font.setPointSize(36)
        font.setUnderline(False)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        
        # HOURLY DATA LABLE 
        self.HOURLY_DATA_LABEL = QtGui.QLabel(self.MIDDLE_FRAME)
        self.HOURLY_DATA_LABEL.setGeometry(QtCore.QRect(10, 330, 181, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.HOURLY_DATA_LABEL.setFont(font)
        self.HOURLY_DATA_LABEL.setStyleSheet(_fromUtf8("Background:url(:/BG_PIC/SMALL_BACKGROUND.png)"))
        self.HOURLY_DATA_LABEL.setAlignment(QtCore.Qt.AlignCenter)
        self.HOURLY_DATA_LABEL.setObjectName(_fromUtf8("HOURLY_DATA_LABEL"))
        self.HOURLY_TEMP_LABEL = QtGui.QLabel(self.MIDDLE_FRAME)
        self.HOURLY_TEMP_LABEL.setGeometry(QtCore.QRect(0, 370, 131, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        
        # HOURLT TEMPERATURE LABEL
        self.HOURLY_TEMP_LABEL.setFont(font)
        self.HOURLY_TEMP_LABEL.setStyleSheet(_fromUtf8("Background:url(:/BG_PIC/SMALL_BACKGROUND.png)"))
        self.HOURLY_TEMP_LABEL.setObjectName(_fromUtf8("HOURLY_TEMP_LABEL"))
        
        # HOURLY PRESSURE LABEL
        self.HOURLY_PRESSURE_LABEL = QtGui.QLabel(self.MIDDLE_FRAME)
        self.HOURLY_PRESSURE_LABEL.setGeometry(QtCore.QRect(140, 370, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.HOURLY_PRESSURE_LABEL.setFont(font)
        self.HOURLY_PRESSURE_LABEL.setStyleSheet(_fromUtf8("Background:url(:/BG_PIC/SMALL_BACKGROUND.png)"))
        self.HOURLY_PRESSURE_LABEL.setAlignment(QtCore.Qt.AlignCenter)
        self.HOURLY_PRESSURE_LABEL.setObjectName(_fromUtf8("HOURLY_PRESSURE_LABEL"))
        
        # HOURLY PRECIPITATION LABEL
        self.HOURLY_PRECIPITATION_LABEL = QtGui.QLabel(self.MIDDLE_FRAME)
        self.HOURLY_PRECIPITATION_LABEL.setGeometry(QtCore.QRect(260, 370, 101, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.HOURLY_PRECIPITATION_LABEL.setFont(font)
        self.HOURLY_PRECIPITATION_LABEL.setStyleSheet(_fromUtf8("Background:url(:/BG_PIC/SMALL_BACKGROUND.png)"))
        self.HOURLY_PRECIPITATION_LABEL.setObjectName(_fromUtf8("HOURLY_PRECIPITATION_LABEL"))
        
        # HOURLY HUMIDITY LABEL
        self.HOURLY_HUMIDTY_LABEL = QtGui.QLabel(self.MIDDLE_FRAME)
        self.HOURLY_HUMIDTY_LABEL.setGeometry(QtCore.QRect(380, 370, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.HOURLY_HUMIDTY_LABEL.setFont(font)
        self.HOURLY_HUMIDTY_LABEL.setStyleSheet(_fromUtf8("Background:url(:/BG_PIC/SMALL_BACKGROUND.png)"))
        self.HOURLY_HUMIDTY_LABEL.setObjectName(_fromUtf8("HOURLY_HUMIDTY_LABEL"))
        
        # HOURLY SUMMARY LABEL
        self.HOURLY_SUMMARY_LABEL = QtGui.QLabel(self.MIDDLE_FRAME)
        self.HOURLY_SUMMARY_LABEL.setGeometry(QtCore.QRect(470, 370, 101, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.HOURLY_SUMMARY_LABEL.setFont(font)
        self.HOURLY_SUMMARY_LABEL.setStyleSheet(_fromUtf8("Background:url(:/BG_PIC/SMALL_BACKGROUND.png)"))
        self.HOURLY_SUMMARY_LABEL.setObjectName(_fromUtf8("HOURLY_SUMMARY_LABEL"))
        
        # HOURLY DATA TEXT EDIT
        self.HOURLY_DATA_TEXTEDIT = QtGui.QTextEdit(WeatherForcast)
        self.HOURLY_DATA_TEXTEDIT.setGeometry(QtCore.QRect(0, 390, 571, 181))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(10)
        font.setUnderline(False)
        self.HOURLY_DATA_TEXTEDIT.setFont(font)
        self.HOURLY_DATA_TEXTEDIT.setStyleSheet(_fromUtf8("BACKGROUND:url(:/BG_PIC/RESULT_TEXTBOX_BG.jpg)"))
        self.HOURLY_DATA_TEXTEDIT.setObjectName(_fromUtf8("HOURLY_DATA_TEXTEDIT"))

        self.retranslateUi(WeatherForcast)
        QtCore.QMetaObject.connectSlotsByName(WeatherForcast)

    def retranslateUi(self, WeatherForcast):
        WeatherForcast.setWindowTitle(_translate("WeatherForcast", "WeatherForcast", None))
        self.PLACE_LABEL.setText(_translate("WeatherForcast", "PLACE :", None))
        self.DATE_LABEL.setText(_translate("WeatherForcast", "DATE :", None))
        self.OK_BUTTON.setText(_translate("WeatherForcast", "OK", None))
        self.OK_BUTTON.clicked.connect(self.forcst)
        self.EMAIL_BUTTON.setText(_translate("WeatherForcast", "E-MAIL", None))
        self.WEATHER_LABEL.setText(_translate("WeatherForcast", "WEATHER", None))
        self.FORCAST_LABEL.setText(_translate("WeatherForcast", "forcast", None))
        self.label.setText(_translate("WeatherForcast", "---------------------------------------------------------------------------------------------------------------------------------------------", None))
        self.GRAPH_BUTTON.setText(_translate("WeatherForcast", "GRAPH", None))
        
        self.CURRENT_TEMPERATURE_LABEL.setText(_translate("WeatherForcast", "TEMPERATURE:", None))
        self.label_2.setText(_translate("WeatherForcast", "---------------------------------------------------------------------------------------------------------------------------------------------", None))
        self.CURRENT_DATA_LABEL.setText(_translate("WeatherForcast", "      CURRENT DATA:", None))
        self.CURRENT_PRESSURE_LABEL.setText(_translate("WeatherForcast", "PRESSURE :", None))
        self.CURRENT_PRECIPITATION_LABEL.setText(_translate("WeatherForcast", "PRECIPITATION:", None))
        self.CURRENT_SUMMARY_LABEL.setText(_translate("WeatherForcast", "SUMMARY:", None))
        self.CURRENT_HUMIDITY_LABEL.setText(_translate("WeatherForcast", "HUMIDITY :", None))
        self.label_5.setText(_translate("WeatherForcast", "---------------------------------------------------------------------------------------------------------------------------------------------", None))
        self.HOURLY_DATA_LABEL.setText(_translate("WeatherForcast", "HOURLY DATA:", None))
        self.HOURLY_TEMP_LABEL.setText(_translate("WeatherForcast", "     TEMPERATURE", None))
        self.HOURLY_PRESSURE_LABEL.setText(_translate("WeatherForcast", "PRESSURE ", None))
        self.HOURLY_PRECIPITATION_LABEL.setText(_translate("WeatherForcast", "PRECIPITATION", None))
        self.HOURLY_HUMIDTY_LABEL.setText(_translate("WeatherForcast", "HUMIDITY ", None))
        self.HOURLY_SUMMARY_LABEL.setText(_translate("WeatherForcast", "SUMMARY", None))

    def forcst(self):
        #print(str(self.PLACE_TEXTBOX.toPlainText()))
        self.HOURLY_DATA_TEXTEDIT.setText(self.PLACE_LINE_EDIT_BOX.toPlainText())
        #x=str(self.DATE_SET.date().toPyDate())
        #print(x)
        
        #namcty(str(self.PLACE_TEXTBOX.toPlainText()))
        

if __name__ == "__main__": 
     app = QtGui.QApplication(sys.argv)
     ex = Ui_WeatherForcast()
     ex.show()
     sys.exit(app.exec_()) 
